# Ponele un nombre único a tu proyecto
sonar.projectKey=2Do-Parcial-Calidad---Merlo-Augusto

sonar.organization=augustomerlo

# Le decimos a Sonar qué archivos tiene que leer (el backend)
sonar.sources=.

# Le decimos a Sonar qué archivos NO debe analizar para no perder tiempo
sonar.exclusions=node_modules/**, **/*.test.js, vercel.json, package*.json, .github/**, sonar-project.properties