name: Integración y Despliegue Continuo (CI/CD)

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Trae el código del repositorio
      - name: Checkout del código
        uses: actions/checkout@v3

      # 2. Prepara el entorno de Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Puedes cambiarlo si usas otra versión

      # 3. Instala las librerías
      - name: Instalar dependencias
        run: npm install

      # 4. Ejecuta tus tests (Si esto falla, el proceso se corta aquí)
      - name: Ejecutar pruebas
        run: npm test